#############################################################################
# Generated by PAGE version 8.1b
#  in conjunction with Tcl version 8.6
#  Mar 04, 2024 05:50:56 AM CST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    system_shutdown_png "./graphics/system-shutdown.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) page-cornsilkdark



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background cornsilk4 -highlightbackground cornsilk4 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 864x683+761+296
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "ScrolledCheckedListbox version 2.0 Demo "
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::frame "$top.tFr48" \
        -borderwidth 2 -relief sunken -width 125 -height 75 
    vTcl:DefineAlias "$top.tFr48" "TFrame2" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.tFr48
    ttk::button "$site_3_0.tBu49" \
        -command "on_btnExit" -image system_shutdown_png -compound none 
    vTcl:DefineAlias "$site_3_0.tBu49" "btnExit" vTcl:WidgetProc "Main" 1
    bind $site_3_0.tBu49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exit Program}
    }
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 812 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::frame "$top.tFr47" \
        -borderwidth 2 -relief sunken -width 860 -height 615 
    vTcl:DefineAlias "$top.tFr47" "TFrame1" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.tFr47
    ttk::frame "$site_3_0.tFr50" \
        -borderwidth 2 -relief sunken -width 355 -height 495 
    vTcl:DefineAlias "$site_3_0.tFr50" "FrameSCLB" vTcl:WidgetProc "Main" 1
    ttk::frame "$site_3_0.tFr51" \
        -borderwidth 2 -relief sunken -width 835 -height 95 
    vTcl:DefineAlias "$site_3_0.tFr51" "FrameMessage" vTcl:WidgetProc "Main" 1
    set site_4_0 $site_3_0.tFr51
    message "$site_4_0.mes52" \
        -background cornsilk4 -borderwidth 2 -cursor crosshair \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -foreground black \
        -highlightbackground cornsilk4 -highlightcolor black -padx 5 -pady 5 \
        -relief groove -text "Message" -textvariable "MessageData" -width 799 
    vTcl:DefineAlias "$site_4_0.mes52" "Message1" vTcl:WidgetProc "Main" 1
    place $site_4_0.mes52 \
        -in $site_4_0 -x 18 -y 11 -width 799 -relwidth 0 -height 72 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::button "$site_3_0.tBu54" \
        -command "on_btnSelectAll" -text "Select All" -compound left \
        -style "bold.TButton" -style bold.TButton 
    vTcl:DefineAlias "$site_3_0.tBu54" "btnSelectAll" vTcl:WidgetProc "Main" 1
    ttk::button "$site_3_0.tBu53" \
        -command "on_btnClearChecks" -text "Clear Checks" -compound left \
        -style "bold.TButton" -style bold.TButton 
    vTcl:DefineAlias "$site_3_0.tBu53" "btnClearChecks" vTcl:WidgetProc "Main" 1
    place $site_3_0.tFr50 \
        -in $site_3_0 -x 10 -y 110 -width 355 -relwidth 0 -height 495 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tFr51 \
        -in $site_3_0 -x 13 -y 6 -width 835 -relwidth 0 -height 95 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu54 \
        -in $site_3_0 -x 420 -y 290 -width 172 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 420 -y 200 -width 172 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr48 \
        -in $top -x 2 -y 2 -width 860 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr47 \
        -in $top -x 2 -y 52 -width 860 -relwidth 0 -height 615 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

